### ISSUE TITLE
Where does Nautilus come from?

### ISSUE THREAD

**Issue by wjk** [canonical/ubuntu-desktop-session-snap#33]
The title of the issue, really. I see that there are references to the nautilus binary in the snap definition here, but nothing that builds or installs it. The only file manager to come up in Snap Store search is KDE Files, and I don’t think we will be using that. 😉

**Comment by sergio-costas** [comment]
The Nautilus binary, along with the whole gnome shell and other binaries, are installed in the `core-base-desktop` snap, the base snap for core desktop: https://github.com/canonical/core-base-desktop/
